### ISSUE TITLE
/api/items

### ISSUE THREAD

**Issue by Boseong-Seo** [wafflestudio20-5/team4-server#11]
- [x] sort request param 추가
- [x] sort request param에 따른 query dsl 다르게 작동하게
- [x] pagination
- [x] pagination & fetch Join 문제 해결
---
### 🐞 Bug 해결 (02.01.)
- [x] sort 제대로 안 되는 문제 해결 (이슈 : mediSkirt에서 낮은 정렬순/높은 정렬순 제대로 작동 X)

**Comment by sukchanlee1** [comment]
wafflestudio20-5/team4-web#24 확인 부탁드립니다.

> - @Boseong-Seo GET api/items가 정상작동하지 않는데, 아마 GET 메소드는 data가 없어서 `@RequestBody` 대신 `@RequestParam`을 써야 하기 때문인 것으로 보입니다. 한번 확인해주시면 감사하겠습니다.

**Comment by hitkoo** [comment]
> [wafflestudio20-5/team4-web#24](https://github.com/wafflestudio20-5/team4-web/pull/24) 확인 부탁드립니다.
> 
> > * @Boseong-Seo GET api/items가 정상작동하지 않는데, 아마 GET 메소드는 data가 없어서 `@RequestBody` 대신 `@RequestParam`을 써야 하기 때문인 것으로 보입니다. 한번 확인해주시면 감사하겠습니다.

이거랑 관련해서 찾아보니 'axios로 get 요청 시 데이터를 request body에 담아서 전송할 수 없다.' 고 합니다. 저희 프론트는 axios 사용하니  notion REST API에서 GET method 전부 Request Body Format을 Request Param Format으로 바꿔야할 것 같습니다

**Comment by Boseong-Seo** [comment]
> [wafflestudio20-5/team4-web#24](https://github.com/wafflestudio20-5/team4-web/pull/24) 확인 부탁드립니다.
> 
> > * @Boseong-Seo GET api/items가 정상작동하지 않는데, 아마 GET 메소드는 data가 없어서 `@RequestBody` 대신 `@RequestParam`을 써야 하기 때문인 것으로 보입니다. 한번 확인해주시면 감사하겠습니다.

@sukchan-0811 제가 석찬님 요청을 이해하지 못해서 여쭤보는데요, 제가 어떤 점을 확인해드리면 되는 걸까요?
insomnia를 가지고서 GET api/items (`@ReqeuestBody` 사용)를 실행시켰을 때에는 정상적으로 잘 작동함을 확인했었거든요.

+ 왠지 프론트에서 오류가 나는 이유가 requestbody에서 category 값을 소문자로 주셔서인 것 같아요! 저도 소문자로 api 요청을 보내보니 에러가 뜨더라고요 (마지막 사진 참고)
프론트 측에서 카테고리 값을 소문자로 주셔도 잘 작동하게끔 수정해 두겠습니다.


![image](https://user-images.githubusercontent.com/90292371/211994439-ff20c676-eafc-437d-9472-43f4105a2c1b.png)
![image](https://user-images.githubusercontent.com/90292371/211994779-c2b46056-f2dc-40da-83f8-92ff8d06b208.png)
![image](https://user-images.githubusercontent.com/90292371/211994915-d969764a-3a87-4788-8ba3-1be6b4ba4fd4.png)

**Comment by sukchanlee1** [comment]
> > [wafflestudio20-5/team4-web#24](https://github.com/wafflestudio20-5/team4-web/pull/24) 확인 부탁드립니다.
> 
> > 
> 
> > > * @Boseong-Seo GET api/items가 정상작동하지 않는데, 아마 GET 메소드는 data가 없어서 `@RequestBody` 대신 `@RequestParam`을 써야 하기 때문인 것으로 보입니다. 한번 확인해주시면 감사하겠습니다.
> 
> 
> 
> @sukchan-0811 제가 석찬님 요청을 이해하지 못해서 여쭤보는데요, 제가 어떤 점을 확인해드리면 되는 걸까요?
> 
> insomnia를 가지고서 GET api/items (`@ReqeuestBody` 사용)를 실행시켰을 때에는 정상적으로 잘 작동함을 확인했었거든요.
> 
> 
> 
> + 왠지 프론트에서 오류가 나는 이유가 requestbody에서 category 값을 소문자로 주셔서인 것 같아요! 저도 소문자로 api 요청을 보내보니 에러가 뜨더라고요 (마지막 사진 참고)
> 
> 프론트 측에서 카테고리 값을 소문자로 주셔도 잘 작동하게끔 수정해 두겠습니다.
> 
> 
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/90292371/211994439-ff20c676-eafc-437d-9472-43f4105a2c1b.png)
> 
> ![image](https://user-images.githubusercontent.com/90292371/211994779-c2b46056-f2dc-40da-83f8-92ff8d06b208.png)
> 
> ![image](https://user-images.githubusercontent.com/90292371/211994915-d969764a-3a87-4788-8ba3-1be6b4ba4fd4.png)
> 
> 

제가 지금 확인할 수는 없는데 제 기억으로는 홈페이지에서 category undefined로 요청을 보냈을 때도 에러가 발생했던 것으로 기억합니다. 만약에 대/소문자가 문제라면 이 경우에는 정상 작동해야 하는 것 아닌가요?

**Comment by Boseong-Seo** [comment]
@sukchan-0811 위 첨부한 사진에서 제일 첫 번째 사진이 category undefined의 경우라고 생각되는데, 혹시 석찬님은 어떻게 요청을 보내셔서 에러가 발생하셨던 건지 말씀해주실 수 있을까요? 캡처 화면이 있으면 보다 이해에 도움이 될 것 같습니다.

**Comment by dongjoocha** [comment]
@Boseong-Seo @sukchan-0811
제가 보기엔 처음에 석찬 님이 요청하신 대로 `@RequestBody`가 아닌 `@RequestParam`으로 프론트측에서 정보를 받아 백에서 처리하는 것이 맞습니다. 

왜냐하면 프론트 측에서 백으로 HTTP Request를 보낼 때 `axios`라는 라이브러리를 사용하는데요, GET Request를 보낼 때 사용하는 `axios.get` 메서드에는 위에서 언급하셨듯이 Request Body를 포함시킬 수가 없습니다 (포함시키려고 하면 컴파일 에러가 납니다). 이게 단순히 `axios.get`의 문제가 아니라 애초에 REST API로 소통을 할 때 POST, PUT 등에는 Request Body를 담지만 GET에는 담지 않는 규칙이 있어서 그런 것 같습니다. 다만 Spring 코드에서도 그렇고 Insomnia에서도 그렇고 GET에 Request Body를 사용할 수 있게 되어 있어서, 보성 님께서 석찬 님이 요청하신 사항을 정확히 파악하기 힘드셨을 것 같습니다.

요약하자면, Insomnia와 Spring 코드에서는 GET 요청으로부터 Request Body를 받아 작업을 수행하는 것이 (이론적으로) 가능하지만, 원칙상 GET 요청에 Request Body를 포함할 수 없는 게 맞고 프론트 측에서도 이에 따라 GET 요청을 보낼 때 Request Body를 포함시킬 수 없습니다. 따라서 앞으로 백엔드에서 GET 요청을 처리할 때에는 `@RequestBody`가 아닌 `@RequestParam`으로 처리해야 할 것 같습니다. `/api/items`도 이와 같이 수정 부탁드립니다!

**Comment by hitkoo** [comment]
오.. 뭔가 안되는게 맞는거 같은데 백을 모르니 제가 잘못하고 있던건지 고민하고 있었는데, 백프론트 다 아는분이 있어서 정말 다행이네요 :)

**Comment by Boseong-Seo** [comment]
오 ... 그러게요 정말 백 프론트를 다 아시는 분이 있어 다행이네요 🥲 
네네 알겠습니다! GET /api/items 는 `@RequestParam`으로 수정하여 다시 PR 올리겠습니다!

**Comment by Boseong-Seo** [comment]
@sukchan-0811 @ksj-hikoo  @TheoLee72 
`@RequestParam`으로 프론트 측 정보 받도록 수정하여 main 브랜치에 merge 해두었습니다. 한번 시도해보시고서 문제 생기시면은 다시 말씀해주세요!

**Comment by sukchanlee1** [comment]
@Boseong-Seo 
인텔리제이에서 앱 실행 시에 다음과 같은 오류가 발생하는데 한번 확인해주실 수 있을까요?
<img width="1381" alt="Screenshot 2023-01-13 at 3 50 07 PM" src="https://user-images.githubusercontent.com/100818542/212255858-b1589231-8f73-4b05-8302-c9da6c0b09e8.png">

**Comment by hitkoo** [comment]
item/:id 는 정상작동하는데 items는 500에러가 뜹니다!

![image](https://user-images.githubusercontent.com/107466434/212257441-71768951-4d50-4729-9150-55906c791ad8.png)

혹시 optional에 문제가 있나해서 category subcategory 전부 지정하고 해봐도 똑같습니다.

![image](https://user-images.githubusercontent.com/107466434/212257715-dd1ddf84-64ce-4e55-86f2-9d8ee89e3619.png)

**Comment by Boseong-Seo** [comment]
@sukchan-0811 
한번 datagrip에서 테이블들을 drop했다가 다시 처음부터 돌려보시겠어요? (아래 첨부 사진 참고)
<br>
<img width="757" alt="image" src="https://user-images.githubusercontent.com/90292371/212271925-a46996e1-ab8e-421e-9020-d7eacdda68d0.png">
위 과정을 items 테이블에 대해서도 동일하게 반복해주시면 됩니다. 반드시 options 테이블 > items 테이블 순으로 해주셔야 합니다!
그렇게 options, items 총 2개의 테이블을 drop한 다음 다시 한번 **Team4Application4.kt** 파일을 run 해봐주시겠어요?
<br>
제가 추측하는 이슈의 원인은 다음과 같습니다. 그래서 위 과정을 수행해보시길 권하는 거구요.

> 1. 이전에 items 테이블에는 `next_item_id` 열(null 값 허용 X)이 존재
> 2. 지난 회의 부로, items 테이블에서 `next_item_id` 열을 제거하기로 하면서, mock data 생성시 items 테이블의 `next_item_id` 열에는 값이 들어가지 않게 함
> 3. 기존의 테이블 규칙에 의하면 `next_item_id` 열로 null 값이 허용이 안 되나, null 값이 들어오게 되면서 에러 발생

만약 위 과정을 반복했는데도 또다시 에러 메시지가 뜬다면,,, 말씀해주세요 !

---
@ksj-hikoo 
제 로컬에서는 잘 작동하는 것 같은데(만약 리액트 상에서의 확인 방법이 잘못되었다면 말씀해주세요), 혹시 intellij나 datagrip 상에서 뜨는 에러 메시지가 무엇인지 확인해주실 수 있을까요?
<br>
![image](https://user-images.githubusercontent.com/90292371/212270758-508b140f-0bf9-4587-80b6-5b79b83dbb72.png)


---

그으리고 ...
제가 저녁 약속이 있어서 오후 11시쯤은 되어야 새로 달아주시는 내용을 확인할 수 있을 것 같습니다.
혹시나 기다리실까봐 미리 말씀드려요 !

**Comment by sukchanlee1** [comment]
어플리케이션 실행은 잘 되는데, 몇 가지 문제가 있어서 말씀드립니다.

1. 지난 회의 때 `Item` 모델의 `image: string` 필드를 `images: string[]` 필드로 바꾸기로 했습니다.
2. Category, SubCategory, Label 등 enum의 값은 노션 페이지에도 소문자로 정리되어 있으니 응답을 보낼 때에도 소문자로 보내주시면 감사하겠습니다.
3. 필수 필드가 아닌 경우, 해당 사항이 없으면 응답에 포함시키지 않아야 합니다. 

예를 들어, 아래와 같은 경우는 그냥 해당 필드들을 비워두고 응답을 보내주시면 될 것 같습니다.
```
{
  ...
  label: "null",
  options: [],
  sale: 0
}
```

**Comment by Boseong-Seo** [comment]
> 어플리케이션 실행은 잘 되는데, 몇 가지 문제가 있어서 말씀드립니다.
> 
> 1. 지난 회의 때 `Item` 모델의 `image: string` 필드를 `images: string[]` 필드로 바꾸기로 했습니다.
> 2. Category, SubCategory, Label 등 enum의 값은 노션 페이지에도 소문자로 정리되어 있으니 응답을 보낼 때에도 소문자로 보내주시면 감사하겠습니다.
> 3. 필수 필드가 아닌 경우, 해당 사항이 없으면 응답에 포함시키지 않아야 합니다.
> 
> 예를 들어, 아래와 같은 경우는 그냥 해당 필드들을 비워두고 응답을 보내주시면 될 것 같습니다.
> 
> ```
> {
>   ...
>   label: "null",
>   options: [],
>   sale: 0
> }
> ```


빠르게 확인해주셔서 감사해요.

1. 네네, 해당 부분 인지하고 있으나, 우선 프론트 측에서 본 api 요청이 잘 시행되는지 확인하는 게 우선이라고 생각되어 image 필드의 수정을 잠시 후순위로 두었습니다. 수정 예정이에요!
2.  넵 알겠습니다! 값을 소문자로 주도록 수정해 둘게요.
3. 네, 해당 사항 또한 다음 PR 때 반영해 두겠습니다.

말씀해주신 사항들 전부 토요일 오전 중으로 마무리 될 듯 보입니다 !

**Comment by Boseong-Seo** [comment]
정리해주신 이슈들 중 2, 3번은 해결했는데, image 필드를 String -> String[] 으로 리팩토링하는 게 시간이 좀 걸리네요.
지금 계속해서 작업 중인데, 마무리되는 대로 멘션 드리겠습니다 !

**Comment by Boseong-Seo** [comment]
@sukchan-0811 @ksj-hikoo @TheoLee72 
석찬님이 정리해주신 이슈들 반영하여 새로 PR 올려두었습니다.
직접 로컬에서 테스트 해보시려면 `itemv2` 브랜치 받으시면은 될 것 같습니다. 아직 메인에 머지되진 않아서요 .!
한번 시도해보시고서 이슈 생기면은 바로 말씀해주세요!
(Team4Application.kt 파일 돌리기 전에 위에서 comment로 작성한 것과 같이 datagrip에서 options, items 테이블 drop 시켜야 합니다 .. ! 🙏 )

**Comment by sukchanlee1** [comment]
@Boseong-Seo 잘 작동하는 것 확인했습니다!! 수고하셨습니다 🙏

**Comment by sukchanlee1** [comment]
@Boseong-Seo 
헉 보성님 정말 죄송하지만... 확인해보니 enum string 값들이 소문자가 아니라 camel case 였어서 `headWear` 등의 경우에 대해서 오류가 납니다. 혹시 이 부분 수정해주실 수 있을까요...? 😭

**Comment by Boseong-Seo** [comment]
@sukchan-0811 헉 ,, 아녜요 제가 잘 챙겼어야 했는데 .. ㅜㅜ 미처 놓쳤었나 봅니다 ..ㅠ 죄송해요
말씀해주신 부분 수정하여 새로 커밋해뒀습니다. `itemv2` 브랜치 다시 받으셔서 확인 부탁드릴게요 !

**Comment by sukchanlee1** [comment]
> @sukchan-0811 헉 ,, 아녜요 제가 잘 챙겼어야 했는데 .. ㅜㅜ 미처 놓쳤었나 봅니다 ..ㅠ 죄송해요 말씀해주신 부분 수정하여 새로 커밋해뒀습니다. `itemv2` 브랜치 다시 받으셔서 확인 부탁드릴게요 !

정상 작동하는 것 확인했습니다~!

**Comment by hitkoo** [comment]
노션 /items에 Request Param sort, Response Body count 추가했습니다.

**Comment by Boseong-Seo** [comment]
@ksj-hikoo 페이지네이션 관련해서도 승진님께 말씀드리면 될까요?

**Comment by Boseong-Seo** [comment]
@ksj-hikoo 승진님 혹시 /items response body에서 아이템의 총 개수(`count`) 대신에 총 페이지 수(`totalPages`)를 return 해드려도 괜찮으신가요 ?

**Comment by hitkoo** [comment]
네 더 좋은 것같아요 :)

**Comment by Boseong-Seo** [comment]
@sukchan-0811 석찬님 본 api response body의 형태를 다음 이슈(#42)의 해결을 위해 조금 수정하려고 하는데 괜찮을지 한번 확인 부탁드릴게요!
노션에 작성한 것과 같이(**[링크](https://www.notion.so/Rest-API-e92a1784fecf4f42832601e65d1e53b5#6eb40532bbd341658201cdd210ed897d)***) Item 모델에서 `options`와 `sex` 필드가 제외된 채로 리턴됩니다. 추가로, 예시 사진도 아래에 첨부합니다.

![image](https://user-images.githubusercontent.com/90292371/214528443-cc60b745-c352-4e8d-98da-85f52c97e358.png)

**Comment by sukchanlee1** [comment]
지금 프론트 측 구현은 `options`는 optional인 반면 `sex`는 필수 필드라서 response에서 빠지게 된다면 리팩토링이 조금 필요할 것 같습니다...! 성별을 response에서 제외할 특별한 이유가 없다면 `options`는 제외하고 `sex`는 채워진 채로 보내주시면 좋을 거 같습니다!
