### ISSUE TITLE
/api/item/:id

### ISSUE THREAD

**Issue by Boseong-Seo** [wafflestudio20-5/team4-server#12]

**Comment by Boseong-Seo** [comment]
@sukchan-0811 석찬님, /api/item/:id 의 response body 형태를 보니 /api/items의 response body와 거의 유사한 듯 보여서 그러는데, 본 api의 response body 형태를 /api/items의 response body(아래 첫 사진 참고)와 통일시키면 어떨까요?

현재 /api/item/:id와 /api/items 의 response body 형식을 맞추기 위해서 그에 맞는 DTO(**ItemResponse**, **ItemRankingResponse**)를 2개 생성해 두었는데요. 위 두 api의 response body의 필드명과 그에 대응되는 값의 타입을 통일시키면, 두 api에서 공통의 DTO를 사용하면 될 것 같아서요. 다시 말해, 지금처럼 굳이 DTO를 2개 생성할 필요가 없을 것 같아서 말씀 드렸습니다.

통일시키게 되면은, 첨부한 두 번째 사진과 같이 필드명이 `item`에서 `items`로 바뀌고, 필드값으로는 Item이 하나만 담긴 리스트로 됩니다.
의견 편하게 말씀해주세요!

![image](https://user-images.githubusercontent.com/90292371/212098352-5ddcc3fd-a515-431f-8288-169eef3e6a1c.png)
![image](https://user-images.githubusercontent.com/90292371/212104816-afbe3f68-cb91-4c9a-ab2f-ad48e96a6c43.png)

**Comment by hitkoo** [comment]
이게  /items는 /item/:id에 비해 필요한 정보가 적어서(review, inquiries) 두 response가 달랐는데 notion 보니까 리뷰랑 문의에 대한 api를 따로 정의하기로 한 것 같네요. 이러면 분리할 이유가 없어 보이긴 합니다.

**Comment by sukchanlee1** [comment]
@Boseong-Seo @ksj-hikoo 
개인적인 의견을 밝히자면 저는 두 API의 DTO를 분리해서 유지하는 게 낫다고 생각하는 편입니다...
 
GET `api/item/:id`는 `id`에 해당하는 단일한 아이템을 가져오기 위한 요청인데 이에 대한 응답으로 `items: Item[]`을 반환하는 것이 조금 직관적이지 않다고 생각해요. 이렇게 응답을 반환하게 된다면 프론트 측에서는 항상 `items[0]`로 응답의 데이터를 참조해야 하고, RESTful하지 않은 측면이 있다고 생각합니다.

그러나 두 API의 DTO를 통일함으로써 백엔드에서 해당하는 요청에 대한 처리가 훨씬 간결해진다면, 그렇게 해도 큰 문제는 없을 것 같습니다. 프론트엔드 측에서 수정해야 할 코드 분량이 그렇게 많은 건 아니라서요!

두 API를 통일하는 것은 두 API의 DTO를 통일하는 것과는 또 다른 문제인데, 역시 같은 이유로 현행 유지하는 것이 낫다고 생각합니다. GET `api/items?category=outer&index=0&count=16`은 GET `api/item/:id`와 명확히 다른 역할을 하는 API이고, 두 요청에 대한 응답의 형태가 비슷하다는 것이 두 API를 하나로 합칠 충분한 이유가 되지는 않는다고 생각합니다.

**Comment by sukchanlee1** [comment]
#11 와도 관련된 내용인데, `item` 모델의 필드에 `reviewCount`를 추가해주시면 좋을 것 같습니다!
노션에는 제가 반영해놓을게요!
