### ISSUE TITLE
/api/user/me

### ISSUE THREAD

**Issue by yangchanhk98** [wafflestudio20-5/team4-server#15]

**Comment by Boseong-Seo** [comment]
@yangchanhk98 제가 어제 PR 리뷰 중에 미처 놓친 거 같은데,
PurchaseEntity가 ReviewEntity와 왜 `@OneToMany`의 관계를 가지도록 설정해두신 건가요?
제 기억상 구매건당 하나의 리뷰 후기만 작성 가능하도록 얘기가 됐던 거 같아서요 .. !
