### ISSUE TITLE
/api/user/me/reviews

### ISSUE THREAD

**Issue by yangchanhk98** [wafflestudio20-5/team4-server#16]
- [ ] purchases에 review 필드 담겨지도록 수정 필요

**Comment by yangchanhk98** [comment]
@TheoLee72 재운님 
Put reviews에 대해 이야기 나누자면

간단히 rating, content, size, color 들은 바꾸는 경우에는 바꿀 내용을 request에 담으면 그대로 수정하면 될 듯 한데, 
images의 경우에는 1)새로운 이미지를 추가하거나 2)기존에 포스트한 이미지를 삭제할 경우에 어떻게 해야 할까요?
PostApi에서는 백엔드에 보내주는 request의 image 자체가 cloudinaryUrl인데 추가할 경우에는 cloudinaryUrl을 보내주기만 하면 되는데, 삭제할 경우에는 어떻게 해야 할 지가 문제입니다.

제 생각에는 RequestBody에
reviewId: number,
rating: number?,
content: String?,
size: String?,
color: String?,
addingImages: String[]?,
removingImages: String[]?,

이렇게 해서 rating, content, size, color는 빈 값인 경우에는 수정하지 않고, 적절한 값이 들어왔을 경우에는 수정하는 것으로 하고,
addingImages에 해당하는 것은 추가하고, deletingImages에 해당하는 것은 삭제하도록 하는 게 어떨까요?
@dongjoocha 동주님, 이 경우에 image를 지울 때에는 업로드 된 image를 삭제하는 Api가 필요할 듯 싶습니다..!

**Comment by dongjoocha** [comment]
@yangchanhk98 @TheoLee72
찬혁 님이 제안하신 것처럼 추가할 이미지랑 삭제할 이미지 따로 받는 게 좋은 것 같습니다.
이미지를 삭제하는 API는 따로 구현하기보다는 그냥 간단하게 review image DB에서 해당 cloudinary URL을 갖고 있는 entity를 삭제하면 될 것 같습니다. (이렇게 하면 cloudinary에는 이미지가 계속 쌓이긴 할 텐데 어차피 업로드 되는 이미지가 많지 않을 것 같아서 토이프로젝트 수준에서는 무방할 것 같습니다)

**Comment by TheoLee72** [comment]
@dongjoocha imageurl 배열을 새로 보내주면 그냥 기존 데이터 지우고 새로 저장하는 방식은 안될까요?

**Comment by dongjoocha** [comment]
> @dongjoocha imageurl 배열을 새로 보내주면 그냥 기존 데이터 지우고 새로 저장하는 방식은 안될까요?
> 
> 

그 방식도 괜찮은 것 같습니다.

**Comment by TheoLee72** [comment]
@yangchanhk98 
<img width="452" alt="image" src="https://user-images.githubusercontent.com/96823216/213653582-ad4b8699-f03b-4611-bfbe-040792f2b386.png">
실제 purchase data 불러와서 api post 했는데도 404 오류가 나네요
request body는 이렇게 날라갔습니다.
<img width="662" alt="image" src="https://user-images.githubusercontent.com/96823216/213653765-24a3df07-312d-4fc2-9e23-458bf2aefcf3.png">
어떤게 문제일까요...? purchaseid는 지금 /api/user/me/purchases에서 받아온 purchaselist에서 각 data의 id로 날리고 있습니다.

**Comment by TheoLee72** [comment]
> @yangchanhk98 <img alt="image" width="452" src="https://user-images.githubusercontent.com/96823216/213653582-ad4b8699-f03b-4611-bfbe-040792f2b386.png"> 실제 purchase data 불러와서 api post 했는데도 404 오류가 나네요 request body는 이렇게 날라갔습니다. <img alt="image" width="662" src="https://user-images.githubusercontent.com/96823216/213653765-24a3df07-312d-4fc2-9e23-458bf2aefcf3.png"> 어떤게 문제일까요...? purchaseid는 지금 /api/user/me/purchases에서 받아온 purchaselist에서 각 data의 id로 날리고 있습니다.

음... purchase가 제대로 받아온게 아닌거 같네요;; 좀더 알아보겠습니다.

**Comment by TheoLee72** [comment]
음 지금 다시 확인해봤는데도 문제가 계속 발생하네요;; 혹시 제가 request body 잘 못 보내고 있나요?

**Comment by Boseong-Seo** [comment]
@TheoLee72 재운님, 좀전 회의에서 말씀드렸던 것처럼 POST review api의 request body가 아래와 같이 되어있어서 그런 것 같습니다. `purchaseId`를 `id`로 바꿔 다시 시도해보시면은 될 것 같아요 ! 그랬는데도 문제 발생하시면은 말씀해주세요
``` {Kotlin}
data class ReviweRequest(
    val id: Long,
    val rating: Long,
    val content: String,
    val size: String,
    val color: String,
    val images: List<String>
)
```

**Comment by TheoLee72** [comment]
@Boseong-Seo 성공했습니다! 아 그런데 api/user/me/purchases에서 response에 review가 안담겨서 오네요 아마 찬혁님과 또 협의해봐야 할 것 같습니다

**Comment by sukchanlee1** [comment]
review POST가 정상적으로 이루어졌을 때 purchase.item의 reviewCount를 1 increment하는 로직이 빠져있는 것 같습니다!

**Comment by dongjoocha** [comment]
> review POST가 정상적으로 이루어졌을 때 purchase.item의 reviewCount를 1 increment하는 로직이 빠져있는 것 같습니다!

해결해드렸습니다~
