### ISSUE TITLE
/api/user/me/purchases

### ISSUE THREAD

**Issue by yangchanhk98** [wafflestudio20-5/team4-server#17]

**Comment by TheoLee72** [comment]
@yangchanhk98 api/user/me/purchases get 할 때 review도 보내주시면 감사하겠습니다!

**Comment by TheoLee72** [comment]
@yangchanhk98 그리고 purchase get 날려주실 때 혹시 datetime아니라 date으로 날려주실 수 있을까요? date으로 notion에 model수정도 해두겠습니다!
