### ISSUE TITLE
/api/user/me/recently-viewed

### ISSUE THREAD

**Issue by yangchanhk98** [wafflestudio20-5/team4-server#19]
- [ ] 최근 본 상품 정렬 제대로 잘 이루어지는지 재확인 필요

**Comment by sukchanlee1** [comment]
상세 페이지 접속 시 세션이 유효한 경우에 한해 POST 요청 보낼 예정

**Comment by Boseong-Seo** [comment]
GET은 @yangchanhk98 님이 맡으시고, 그 외 POST는 제가 맡기로 했습니다 !

@sukchan-0811 시간 되실 때 POST api의 request body 및 response body 양식을 Notion Rest API 문서에 작성해주시면 감사하겠습니다 !
