### ISSUE TITLE
/api/user/me/item-inquiry

### ISSUE THREAD

**Issue by yangchanhk98** [wafflestudio20-5/team4-server#20]
- [x]  DB에 쌓이는 type → Enumerated type을 string으로 수정
- [x]  item inquiry 수정 시 modifiedDateTime이 update되도록
- [ ]  item-inquiry API response 형태 수정     
- [x] Inquiry 에 option 정보가 안 나가고 있음 → option 필드 추가
- [x] inquiryEntity에서 images 필드를 > image1, image2, image3으로 수정
- [x] reviewEntity에서도 마찬가지
- [x] 페이지네이션
 ---
- 고민 사항
    - 상품 문의를 delete 한다고 해서 DB에서 아예 날리는 게 맞을까?
    - 그냥 삭제했다고 marking만 하는 게 낫지 않을까? → deleted, deletedDateTime과 같은 필드명 사용해서 .. ! inquiry 정보는 많이 쓰일 거 같은데

**Comment by Boseong-Seo** [comment]
@ksj-hikoo @TheoLee72 
승진님, 재운님 ! 노션에 GET, PUT, DELETE item-inquiry api들 작성해뒀는데, 한번 확인 부탁드릴게요
확인해보시고 수정 필요하시면 말씀해주세요

**Comment by TheoLee72** [comment]
괜찮은 것 같습니다!

**Comment by TheoLee72** [comment]
@Boseong-Seo 이 api는 get put delete 모두 저랑 협의하시면 될것같습니당

**Comment by TheoLee72** [comment]
그런데 notion에는 /api/user/me/item-inquiries라 적혀 있던데 뭐가 맞는건가요...?

**Comment by Boseong-Seo** [comment]
> 그런데 notion에는 /api/user/me/item-inquiries라 적혀 있던데 뭐가 맞는건가요...?

좀전에 슬랙으로도 말씀드렸지만, 노션에 적힌 걸 따라주시면 됩니다 .. !

**Comment by Boseong-Seo** [comment]
@TheoLee72 재운님, GET /api/user/me/item-inquiry 의 response body 포맷을 약간 수정했는데, 이렇게 전달드려도 괜찮을지 확인 부탁드려요 ! (**[링크](https://www.notion.so/Rest-API-e92a1784fecf4f42832601e65d1e53b5#3dbbba20967f45a8b73727d601e48d08)***)
그리고, 페이지네이션을 위한 총 페이지 수 정보도 함께 전달드려야 할지 확인 부탁드릴게요

- 주요 수정사항
   + response body에서 유저 정보 삭제
   + 상품 정보 중에서도 반드시 전달해야 하는 정보만을 전달하도록 수정

**Comment by TheoLee72** [comment]
네 수정사항들은 괜찮을 것 같습니다. 사실 페이지네이션 생각을 못하고 있었는데 하려면 index랑 count 보내드리고 또 count에 따라 총 페이지수 보내주시는 방식으로 하면 될까요? 다른데는 어떻게 하고 있는지 모르겠네요

**Comment by Boseong-Seo** [comment]
> 네 수정사항들은 괜찮을 것 같습니다. 사실 페이지네이션 생각을 못하고 있었는데 하려면 index랑 count 보내드리고 또 count에 따라 총 페이지수 보내주시는 방식으로 하면 될까요? 다른데는 어떻게 하고 있는지 모르겠네요

기존대로 API 콜 주시면은 제가 response body에 총 페이지 수(`totalPages`) 를 드리는 방식으로 하고 있습니다.  그래서 여기서도 GET의 response body에 있는 totalPages 가지고서 총 페이지 수 보시면 될 것 같아요

**Comment by TheoLee72** [comment]
@Boseong-Seo 아 그럼 notion rest api 수정해주실 수 있을까요? 음 그런데 제가 index count를 보내드려야 totalPages를 계산해주실 수 있는거 아닌가요?

**Comment by Boseong-Seo** [comment]
@TheoLee72 네네 그래서 원래대로(이게 원래대로가 아니엇군요.!..ㅠ) index와 count를 API콜 때 한 번만 전달주시면 된다는 뜻이었습니다..!
GET api/user/me/item-inquiries?index=&count= 로 API 콜하시면,
제가 response body에 해당 페이지에 노출되어야 할 inquiries 리스트와 총 페이지 수를 전달 드린단 말씀이었어요

**Comment by TheoLee72** [comment]
> @TheoLee72 네네 그래서 원래대로(이게 원래대로가 아니엇군요.!..ㅠ) index와 count를 API콜 때 한 번만 전달주시면 된다는 뜻이었습니다..! GET api/user/me/item-inquiries?index=&count= 로 API 콜하시면, 제가 response body에 해당 페이지에 노출되어야 할 inquiries 리스트와 총 페이지 수를 전달 드린단 말씀이었어요

넵 알겠습니당!
