### ISSUE TITLE
/api/item/:id/reviews

### ISSUE THREAD

**Issue by Boseong-Seo** [wafflestudio20-5/team4-server#25]
- [x] pagination 작업

**Comment by TheoLee72** [comment]
{
		"index"?: number   # default 0
		"count"?: number   # default 5
}

rest api 수정해주신거 봤는데요, 그럼 만약 index: 1, count: 10 이렇게 request body 보내면
11번부터 20번까지 보내주시는건가요? (맨 처음 review가 1번이라는 가정에서)

**Comment by TheoLee72** [comment]
{
		"id": number,
		//"user": User,        #comment.review.purchase.user에서 찾을 수 있어서 삭제함
		"review": Review     #comment와의 양방향 관계를 위해 일단 두었음.      
		"content": string,
		"createdDateTime": LocalDateTime,
}
지금 model다시 보고 있는데 comment model에 이렇게 적혀있는데 
user살아있어야 되지 않을까요? comment.review.purchase.user은 review쓴 사람이지 comment 쓴 사람은 아닌 것 같아서요!

**Comment by Boseong-Seo** [comment]
> { "index"?: number # default 0 "count"?: number # default 5 }
> 
> rest api 수정해주신거 봤는데요, 그럼 만약 index: 1, count: 10 이렇게 request body 보내면 11번부터 20번까지 보내주시는건가요? (맨 처음 review가 1번이라는 가정에서)

댓글 달아주신 거 이제 봤네요 ㅜㅜ 네네 말씀해주신대로 response body를 드릴 예정입니다.

**Comment by Boseong-Seo** [comment]
> { "id": number, //"user": User, #comment.review.purchase.user에서 찾을 수 있어서 삭제함 "review": Review #comment와의 양방향 관계를 위해 일단 두었음. "content": string, "createdDateTime": LocalDateTime, } 지금 model다시 보고 있는데 comment model에 이렇게 적혀있는데 user살아있어야 되지 않을까요? comment.review.purchase.user은 review쓴 사람이지 comment 쓴 사람은 아닌 것 같아서요!

이 comment model은 제가 작성한 게 아니라 user 필드가 왜 삭제되어 있는진 모르겠지만, 
네네 말씀해주신 것처럼 user가 필요할 것 같네요 ! 제가 그렇게 노션 문서 수정해둘게요

**Comment by TheoLee72** [comment]
생각해보니 저번에 회의 때 
<img width="555" alt="image" src="https://user-images.githubusercontent.com/96823216/212913530-976e3f8d-83a6-405f-b971-a69822229ad4.png">
최신순, 댓글순, 높은평점순, 낮은평점순은 하기로 한 것 같은데 이건 어떻게 request body에 넣을까요?

그리고
<img width="899" alt="image" src="https://user-images.githubusercontent.com/96823216/212914145-460ef8aa-06e6-4d0b-bbca-46f70f650e71.png">
맨 아래에 페이지 수를 미리 띄워야되는데 혹시 reviews전체 개수를 count로 나눠서 올림 한 값을 response body에 넣어서 보내주실 수 있을까요?

**Comment by Boseong-Seo** [comment]
> 생각해보니 저번에 회의 때 <img alt="image" width="555" src="https://user-images.githubusercontent.com/96823216/212913530-976e3f8d-83a6-405f-b971-a69822229ad4.png"> 최신순, 댓글순, 높은평점순, 낮은평점순은 하기로 한 것 같은데 이건 어떻게 request body에 넣을까요?
> 
> 그리고 <img alt="image" width="899" src="https://user-images.githubusercontent.com/96823216/212914145-460ef8aa-06e6-4d0b-bbca-46f70f650e71.png"> 맨 아래에 페이지 수를 미리 띄워야되는데 혹시 reviews전체 개수를 count로 나눠서 올림 한 값을 response body에 넣어서 보내주실 수 있을까요?

1. 최신순, 댓글순, ~~ 을 안 하기로 한 것 아니었나요 ..? 제 기억상 안 하기로 정리됐던 것 같은데, 저도 기억이 정확하지 않아서 잘 모르겠네요 ㅜㅜ

2. 아하 네네 알겠습니다. 그러면 아래와 같은 양식으로 response body를 드리면 될까요?
```
{
    'reviews' : [{
         }, ... , {
      }],
    'totalPage' : number
}
```

**Comment by sukchanlee1** [comment]
@Boseong-Seo 상세 페이지를 제가 작업하기로 해서 앞으로는 저랑 의논하시면 될 것 같습니다.

다른 건 지금까지 논의된대로 하면 될 것 같은데, item 모델에 reviewcount가 있기 때문에 이 api의 response body에 totalPage는 보내주실 필요가 없습니다. 그냥 review의 array만 보내주시면 될 듯합니다.

**Comment by Boseong-Seo** [comment]
@sukchan-0811 
그래서 저희 리뷰 정렬을 위에서 재운님이 말씀해주신 것과 같이 "_최신순, 댓글순, 등등으로의 정렬_"을 하기로 했었나요 .?
제 기억상에는 하지 말자고 했던 것 같은데, 혹시 몰라 여쭤봅니다.
그리고 만약 다양한 기준으로 리뷰 정렬을 하고자 한다면, 그에 맞는 request param을 제안해주시면 될 것 같습니다 !

**Comment by sukchanlee1** [comment]
@Boseong-Seo 
사실 저도 잘 기억이 안 납니다...ㅜ

**Comment by dongjoocha** [comment]
> @Boseong-Seo 사실 저도 잘 기억이 안 납니다...ㅜ

제 기억엔 하기로 했던 것 같긴 한데, 일단 안 하는 방식으로 구현 후에 나중에 여유 되면 추가 구현하시면 될 것 같습니다..!

**Comment by sukchanlee1** [comment]
GET reviews에서 user 필드가 빠져있는 것 같습니다!
<img width="835" alt="Screenshot 2023-01-28 at 12 30 18 PM" src="https://user-images.githubusercontent.com/100818542/215239886-017430b1-c806-466a-a5ef-66cd8768443e.png">

**Comment by sukchanlee1** [comment]
count를 1로 해도 2개 이상의 review가 오는 현상이 있습니다...ㅜ
<img width="835" alt="Screenshot 2023-01-28 at 4 37 27 PM" src="https://user-images.githubusercontent.com/100818542/215253569-5080a694-ef54-4928-9a9d-9ab61b5fe5e6.png">

**Comment by Boseong-Seo** [comment]
@sukchan-0811 확인했습니다! 금일 내로 수정해서 다시 PR 올리겠습니다. 확인 감사해요

**Comment by sukchanlee1** [comment]
> @sukchan-0811 확인했습니다! 금일 내로 수정해서 다시 PR 올리겠습니다. 확인 감사해요

지난 코딩 모임 때 동주 님께서 바로 반영해서 수정해주셨습니다!
