### ISSUE TITLE
/api/item/:id/inquiries

### ISSUE THREAD

**Issue by Boseong-Seo** [wafflestudio20-5/team4-server#26]
- [x] pagination 작업

**Comment by TheoLee72** [comment]
@Boseong-Seo 
"type": string,                 # size | delivery | restock | detail
"option"?: string,            # 문의를 남기려는 상품 옵션
"isSecret": boolean,        # 비밀글 여부
"title": string,            
"content": string,
"images"?: string[],

여기서 option은 없으면 빈 string "", images는 없으면 빈 array []를 보내게 될것 같은데 그렇게 해도 될까요?

**Comment by TheoLee72** [comment]
아니면 그냥 아예 보내지 말까요?

**Comment by Boseong-Seo** [comment]
@TheoLee72 아예 안 보내주시면 될 것 같습니다!
